id: IAA70F28D
legacy_id: P006834
ocr_import_info:
  bdrc_scan_id: W1AC213
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T12:55:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:58:00.879393+00:00'
last_modified: 2022-08-30 23:58:31.560309
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC213
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1AC213
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་བུདྡྷ་པ་ལི་ཏ།
  author: སློབ་དཔོན་སངས་རྒྱས་བསྐྱངས།
statistics:
  ocr_word_mean_confidence_index: 0.8149325834499388
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD18520:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18520
      total_pages: 476
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18520.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8149325834499388
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
